### ISSUE TITLE
Getting the backend stats does not work

### ISSUE THREAD

**Issue by pieterbos** [newrelic/statsd-infra-backend#1]
https://github.com/newrelic/statsd-infra-backend/blob/master/lib/newrelic-infra.js#L368 will log 'TypeError: Cannot convert undefined or null to object' because Object.keys() is called without an argument

**Comment by pieterbos** [comment]
Of course this line should be:
```Object.keys(nriStats).forEach(function(stat) {```

**Comment by sbz** [comment]
While using the NewRelic StatsD Integration, I have encountered the same problem and I have submitted the following PR #2 to solve it.

**Comment by areina** [comment]
@pieterbos @sbz this has been solved after merging PR#2.
