### ISSUE TITLE
Backend doesn't process 'sets' properly 

### ISSUE THREAD

**Issue by akiryiak** [newrelic/statsd-infra-backend#5]
Hi team,

I'm trying to send Kong api-gateway metrics to NewRelic through StatsD.
Most of the metrics are processed properly, only with sets I have an issue. 

> /usr/share/statsd/node_modules/@newrelic/statsd-infra-backend/lib/newrelic-infra.js:251
evalRule(rule, metricName + '.count', sets[metricName].size());
node: ^
node: TypeError: sets[metricName].size is not a function
node: at /usr/share/statsd/node_modules/@newrelic/statsd-infra-backend/lib/newrelic-infra.js:251:62
node: at Array.forEach (native)
node: at /usr/share/statsd/node_modules/@newrelic/statsd-infra-backend/lib/newrelic-infra.js:250:11
node: at Array.forEach (native)
node: at nriCollectMetrics (/usr/share/statsd/node_modules/@newrelic/statsd-infra-backend/lib/newrelic-infra.js:249:21)
node: at EventEmitter.nriFlush (/usr/share/statsd/node_modules/@newrelic/statsd-infra-backend/lib/newrelic-infra.js:357:25)
node: at emitTwo (events.js:111:20)
node: at EventEmitter.emit (events.js:191:7)
node: at emitFlush (/usr/share/statsd/stats.js:131:19)
node: at Object.process_metrics (/usr/share/statsd/lib/process_metrics.js:126:5)

Metric is: kong.foo.user.uniques:foobaruser|s
newrelic-statsd-backend v.1.0.1
npm@3.10.10
node v6.14.3

Thanks in advance,
Artur

**Comment by alejandrodnm** [comment]
Hi @akiryiak, well look into it and let you know.
