### ISSUE TITLE
Missing datapoints on statsd payload

### ISSUE THREAD

**Issue by IvanJasjko** [newrelic/statsd-infra-backend#6]
Hi!
 
We are running Statsd 0.8.0 on Debian 9 (Stretch) to connect Hashicorp’s Nomad Telemetry to New Relic.
Here are the typical rules that we are using for our config:
 
---

{
  port: "8125"
, address: "localhost"
, backends: ["@newrelic/statsd-infra-backend"]
, keyNameSanitize: true
, dumpMessages: false
, newrelic: {
  port: 8001,
  rules: [
    {
      matchExpression: "nomad.client.allocs.cpu.*",
      metricSchema: "{app}.{client}.{type}.{resource}.{metricName}.{jobName}.{taskGroupName}.{allocationID}.{taskName}.{ipAddress}",
      eventType: "testCPU",
    }

---

Here are sample messages dumped by Nomad:
Note the different values for jobName: replicator, fabio, jenkins-efee8ba4ff09

---
 
10 Oct 09:56:25 - DEBUG: nomad.client.allocs.cpu.total_percent.jenkins-efee8ba4ff09.jenkins-slave-taskgroup.ec8dd29b-edcb-efa8-67e9-f52a43cab9f8.jenkins-slave.ip-10-149-1-221:0.065606|g
10 Oct 09:56:26 - DEBUG: nomad.client.allocs.cpu.total_percent.replicator.replicator.6462340a-dddd-c6b4-2a58-56b071dba53e.replicator.ip-10-149-1-221:0.026463|g
10 Oct 09:56:26 - DEBUG: nomad.client.allocs.cpu.total_percent.fabio.fabio.3a1e0344-c30b-db26-4ba0-e6bbdeffc89a.fabio.ip-10-149-1-221:0.580280|g
 
---
 
However, the payload that sends only one of these metrics to New Relic seemingly chosen at random.
For instance, this is the payload that we see in debug mode:

---
 
10 Oct 09:59:28 - DEBUG: Matching keys against rule expressions: [nomad.client.allocs.cpu.*]
10 Oct 09:59:28 - DEBUG: Matched keys 0. Total keys: 81
10 Oct 09:59:28 - DEBUG: Sending payload: {"name":"com.newrelic.statsd","integration_version":"0.1.0","protocol_version":"1","metrics":[{"event_type":"testCPU","app":"nomad","client":"client","type":"allocs","resource":"cpu","jobName":"replicator","taskGroupName":"replicator","allocationID":"6462340a-dddd-c6b4-2a58-56b071dba53e","taskName":"replicator","ipAddress":"ip-10-149-1-221","total_percent":0.020037,"label.role":"cpu","label.job":"replicator","system":0,"user":0,"throttled_time":0,"throttled_periods":0,"total_ticks":0.500927}],"inventory":{},"events":[]}
10 Oct 09:59:28 - DEBUG: Payload sent successfully
10 Oct 09:59:38 - DEBUG: Matching keys against rule expressions: [nomad.client.allocs.cpu.*]
10 Oct 09:59:38 - DEBUG: Matched keys 0. Total keys: 81
10 Oct 09:59:38 - DEBUG: Sending payload: {"name":"com.newrelic.statsd","integration_version":"0.1.0","protocol_version":"1","metrics":[{"event_type":"testCPU","app":"nomad","client":"client","type":"allocs","resource":"cpu","jobName":"replicator","taskGroupName":"replicator","allocationID":"6462340a-dddd-c6b4-2a58-56b071dba53e","taskName":"replicator","ipAddress":"ip-10-149-1-221","total_percent":0.024181,"label.role":"cpu","label.job":"replicator","system":0,"user":0,"throttled_time":0,"throttled_periods":0,"total_ticks":0.604523}],"inventory":{},"events":[]}
10 Oct 09:59:38 - DEBUG: Payload sent successfully
 
---
 
As you can see only replicator data is being sent, with jenkins and fabio being left behind. As a result, we are getting incomplete information in our New Relic tables.

We would like to know if you have any ideas on why this is the case?

P.S If console output is specified as backend instead of New Relic then all data is being put put on payload as expected.

**Comment by varas** [comment]
This should be fixed with https://github.com/newrelic/statsd-infra-backend/pull/7

**Comment by alejandrodnm** [comment]
This has been released in the version `1.0.2`
